name: flowo_client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+6

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  table_calendar: ^3.0.0
  uuid: ^4.5.1
  bloc: ^9.0.0
  syncfusion_flutter_calendar: ^29.1.35
  syncfusion_flutter_charts: ^29.1.35
  path_provider: ^2.0.11
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.8
  hive: ^2.0.1
  hive_flutter: ^1.1.0
  universal_io: ^2.0.4
  image_picker: ^1.1.2
  provider: ^6.0.0
  logger: ^2.5.0
  shared_preferences: ^2.0.6
  datetime_picker_formfield: ^2.0.0
  cupertino_sidebar: ^1.0.1
  flutter_local_notifications: ^19.0.0
  http: ^1.2.0
  intl: ^0.19.0
  # Video and audio packages for ambient feature
  video_player: ^2.8.2
  chewie: ^1.7.5
  just_audio: ^0.9.36
  cached_network_image: ^3.3.1
  # Email package
  mailer: ^6.1.0
  timezone: ^0.10.0
  # File sharing
  share_plus: ^10.1.4
  #youtube player
  youtube_player_flutter: ^9.1.1
  #webview
  flutter_inappwebview: ^6.1.5
  audio_session: ^0.1.25
  flutter_timezone: ^4.1.0
  easy_refresh: ^3.4.0
  lottie: ^3.3.1
  flutter_slidable: ^4.0.0
dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/avatar.png
    - assets/ambient/videos/
    - assets/ambient/audio/
    - assets/ambient/thumbnails/
    # - assets/tutorial/
    - lib/assets/lottifile/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/icon/app_icon.png"
