// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMIJIccaR6V1nYcZkF6bq4_Ffobwc65I',
    appId: '1:476100136448:web:14ace5f02306ea9cd152e5',
    messagingSenderId: '476100136448',
    projectId: 'flowo-fc2e5',
    authDomain: 'flowo-fc2e5.firebaseapp.com',
    storageBucket: 'flowo-fc2e5.firebasestorage.app',
    measurementId: 'G-2H68JKCY09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC0OQuKymntdf_Ivw8NBtqTPvEd4J555c',
    appId: '1:476100136448:android:87bddb23d8ec45f6d152e5',
    messagingSenderId: '476100136448',
    projectId: 'flowo-fc2e5',
    storageBucket: 'flowo-fc2e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAql0gT0GKm34nFdghWbQcS8txphrqdwE',
    appId: '1:476100136448:ios:e763df230e40ff21d152e5',
    messagingSenderId: '476100136448',
    projectId: 'flowo-fc2e5',
    storageBucket: 'flowo-fc2e5.firebasestorage.app',
    iosBundleId: 'com.7wells.flowo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAql0gT0GKm34nFdghWbQcS8txphrqdwE',
    appId: '1:476100136448:ios:e763df230e40ff21d152e5',
    messagingSenderId: '476100136448',
    projectId: 'flowo-fc2e5',
    storageBucket: 'flowo-fc2e5.firebasestorage.app',
    iosBundleId: 'com.7wells.flowo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzMIJIccaR6V1nYcZkF6bq4_Ffobwc65I',
    appId: '1:476100136448:web:ea13794522a211d2d152e5',
    messagingSenderId: '476100136448',
    projectId: 'flowo-fc2e5',
    authDomain: 'flowo-fc2e5.firebaseapp.com',
    storageBucket: 'flowo-fc2e5.firebasestorage.app',
    measurementId: 'G-EGC6S57TYJ',
  );
}
